### ISSUE TITLE
Toevoegen: Trauma helicopter

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#114]
Voor ambulance is het misschien leuk en handig om ook een heli te hebben om snel ergens te kunnen zijn.
Weet niet of deze samen kan aangezien er ook 1 van heli is en van weazel nieuws (mochten we die ooit willen gaan gebruiken)

https://www.gta5-mods.com/paintjobs/lifeliner-traumahelikopter-eurocopter-ec-135-els-replace-dutch-nederlands

**Comment by niekschoemaker** [comment]
Done
