### ISSUE TITLE
Bij Job Berging - Duiker zit er iets gekoppeld aan de F10 knop.

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#120]
Ik probeer nu de berging - duiker job en als ik wil zien hoeveel politie .e.d online zijn druk ik op F10.
Dan staat er links boven het GPS een melding: Je moet in een dienstvoertuig zitten!

Met de F10 knop kan je de job starten en stoppen.
Erg lastig dus als je bezig bent en even wilt kijken via F10 wie er online zijn ofzo. (dan stop je de job)

**Comment by Willem-Dekker** [comment]
Is veranderd naar F9
