### ISSUE TITLE
Auto's spawnen spontaan in op de weg en exploderen hierdoor

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#121]
Dit is niet te reproduceren maar dit gebeurd soms. 
Je hoort explosies en soms op de weg zie je 2 dezelfde auto's

**Comment by pelikaanjpeg** [comment]
Is voor zover ik weet een issue van OneSync maar zal het ff nachecken of meer mensen hetzelfde probleem hebben

**Comment by Ventrex** [comment]
Viel me vooral op op snelwegen, gisteren nog 4x gezien tijdens het testen van jobs

**Comment by Ventrex** [comment]
Was onesync ofzo. Zie het nog wel eens maar bijna niet meer
