### ISSUE TITLE
Voertuig borg van jobs op 0 zetten ivm CheatEngine Abuse

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#122]
Gemeld door Brothasx, mensen kunnen dmv cheat engine de borg verhogen zodat ze meer terug krijgen wanneer ze de auto inleveren.

**Comment by niekschoemaker** [comment]
Het deze glitch even na gecontroleerd, volgens mij is deze in de laatste versie van esx_jobs al gefixxed sinds het via de database gaat en hij puur de vehicleHealth van de client pakt en kijkt of deze niet hoger is dan de max op de server en geeft dan het geld terug.
