### ISSUE TITLE
Idee: Auto verhuur 

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#124]
Momenteel rijdt de hele server met auto's. 
Zou leuk zijn als dat nog steeds kan maar dan als huren ipv direct kopen.
IRL kan je ook niet direct een auto kopen maar lease of huur je deze eerst (of helemaal niet natuurlijk)

https://forum.fivem.net/t/release-esx-carrental/127465

**Comment by Willem-Dekker** [comment]
denk niet dat dit slim is IVM het niet terug brengen er van

**Comment by Ventrex** [comment]
Wat Willem aangeef is idd goeie. Maar als je hem niet kan laten verkopen of uit de garage kan halen na bepaalde tijd (7 ingame dagen) dan is die na herstart of offline gaan kwijt en ben je borg kwijt.

**Comment by Ventrex** [comment]
Niet meer van toepassing: fiets verhuur eventueel en je kan redelijk snel een auto kopen
