### ISSUE TITLE
Idee: Salaris om 08:00 ingame ipv elke 10 minuten

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#125]
Momenteel krijgen spelers elke 10 minuten (uit mijn hoofd) geld op hun rekening.
Is het aan te passen dat die elke ingame dag gebeurd.

Bijvoorbeeld om 08:00
Als dat te lang duur (dus 20 minuten ofzo) dan kan salaris verhoogd worden.

**Comment by Willem-Dekker** [comment]
het is nu elke 24 min volgns mij dat is ook de dag duur van gta

**Comment by Willem-Dekker** [comment]
alle lonen zijn aangepast op de 10 min
