### ISSUE TITLE
Ventrex rechten geven om ook iets te kunnen doen op Github dan alleen melden

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#129]
Ik kan niets met project doen.
Ook kan ik niets sluiten wanneer het is opgepakt.

Paar dagen terug al gevraagd maar nog niet gedaan. Daarom maar een issue van maken

**Comment by Willem-Dekker** [comment]
Er is een paar dagen geleden een invite gestuurd die moet je accepteren.

**Comment by Ventrex** [comment]
Graag opnieuw sturen want heb niets ontvangen

**Comment by Willem-Dekker** [comment]
ik heb daar geen rechten voor
