### ISSUE TITLE
Auto wordt weggesleept wanneer je offline gaat (ook bij server crash)

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#130]
Wanneer je auto niet in de garage staat en je gaat offline of de server crasht ben je je auto kwijt.
Deze moet je tegen betaling weer uit opslag halen.

Kan getest worden door auto uit garage te halen en offline te gaan.

Mogelijke opties: Wanneer op slot kan die niet weggehaald worden tenzij via ANWB weggesleept

**Comment by Willem-Dekker** [comment]
kan je niet instellen en is denk ik wel een mooie feature om te hebben houd de straat schoon

**Comment by Ventrex** [comment]
Heel veel klachten zijn er nu al, helemaal als de server crasht en mensen moeten betalen om auto terug te krijgen of ver afgelegen liggen.

**Comment by Willem-Dekker** [comment]
Dit is op elke server zo. het is een item voor na de realease maar denk dat de fucus nu meer moet liggen op het af krijgen voor de release

**Comment by Ventrex** [comment]
Ga jij de klachten afhandelen straks? Zal een dagtaak worden namelijk

**Comment by niekschoemaker** [comment]
De game zelf verwijderd de auto's, zijn opgeslagen in RAM.
