### ISSUE TITLE
Taxi zwart maken ipv geel

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#131]
Momenteel is de taxi geel. Als je /car Taxi doet of de taxijob kiest en je auto neemt is deze geel.

De stream file zou die zwart moeten zijn met een taxi logo bovenop.

**Comment by niekschoemaker** [comment]
carvariations van Politie_Audi_A6 aangepast om carvariations.meta er bij in te hebben, standaard kleur is nu metallic zwart.
