### ISSUE TITLE
Toevoegen Tablet met regels/ keybinds / uitleg

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#132]
Elke speler een tablet geven zodat ze de regels / keybinds / jobs / autos en uitleg e.d. kunnen terug vinden
https://forum.fivem.net/t/in-game-tablet-with-web-based-cad-mdt-support/108769

**Comment by niekschoemaker** [comment]
Is al toegevoegd (wel een andere) plugin heet tab, staat atm standaard uit. Moet alleen nog vertaald worden en ingesteld worden. Plugin is te vinden onder [mods]/tab/
