### ISSUE TITLE
Chat Roles zoals Betterchat in Rust

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#133]
Chat is nu al mooi maar met deze optie is het zichtbaar wie staff is.
Eventueel kan die gekoppeld worden met RUST rechten: https://forum.fivem.net/t/release-chat-roles-updated-5-30-18-tutorial-released/28510

**Comment by Willem-Dekker** [comment]
Is denk ik niet helemaal voor roleplay
