### ISSUE TITLE
Sending heartbeat to live-internal.fivem.net:30110 maar site is onbereikbaar

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#135]
Ik zie in de log diverse keren bovenstaande melding. 
Als je deze opzoekt lijkt deze down te zijn.

Gaat dit voor problemen zorgen of kan dit geen kwaad?
Het kan ook dat ik verkeerd kijk en dit geen kwaad kan.

**Comment by Willem-Dekker** [comment]
kan geen kwaad is een itern iets
