### ISSUE TITLE
screenshot-basic niet geinstalleerd op de server.

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#136]
In de log op de server staat de volgende regel:
screenshot-basic is not installed on this Server, this means that the screenshot feature will not be available, please download and install it from:
https://github.com/citizenfx/screenshot-basic

**Comment by niekschoemaker** [comment]
Yarn werkt niet op Linux en screenshot-basic gebruikt yarn en is een minor issue (print screen werkt volgens mij net zo goed)
