### ISSUE TITLE
Nieuwe versie moneywash / black money

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#137]
We gebruiken momenteel esx_moneywash uit 2017 / begin 2018
Echter is deze niet meer in support en is er een nieuwe mod: https://forum.fivem.net/t/release-esx-blackmoney-moneywash/123533

**Comment by niekschoemaker** [comment]
Ziet er niet veel beter uit dan de versie die we nu hebben, die we nu hebben heb ik in principe ook al volledig zelf geschreven gebaseerd op een bestaande snippet ergens en die wordt ook niet gesupport
