### ISSUE TITLE
Crimal record system

### ISSUE THREAD

**Issue by Nander0320** [pelikaanjpeg/TDAFiveM#139]
Systeem om een crimineel record in bureau aan te maken werkt niet goed, Hij geeft bij elke naam die je invult aan dat de naam niet geldig is.

Je kunt het nachecken in het politie bureau van de stad achter de informatiebalie

**Comment by Willem-Dekker** [comment]
kan je graag ff kijken naar, het format die er staat voor issues :)

**Comment by niekschoemaker** [comment]
Werkt bij mij persoonlijk naar behoren, had volgens mij met DOB format te maken. Artifact van prefiltering tijden
