### ISSUE TITLE
Auto's despawnen niet

### ISSUE THREAD

**Issue by Nander0320** [pelikaanjpeg/TDAFiveM#140]
Bij garage verdwijnen auto's soms niet als mensen deze opslaan waarna alles helemaal volloopt en het een puinhoop word.

Je kunt het testen bij garage blokkenpark door een paar keer je auto uit en in de garage te zetten

**Comment by Willem-Dekker** [comment]
graag aan format gebruiken die is aangegeven

**Comment by niekschoemaker** [comment]
Gefixed
