### ISSUE TITLE
APK keuring plug in bekijken

### ISSUE THREAD

**Issue by Hagrid123** [pelikaanjpeg/TDAFiveM#160]

**Comment by Willem-Dekker** [comment]
Kan op basis van kilometer stand dan je bv na 1000 km moet keuren. 
Dan moet de spedometer het wel weergeven in het beeld van de gebuiker wat de huidige stand is.

**Comment by Willem-Dekker** [comment]
Keur rapport, maken en meer slijtage hoe hoger de km stand is
