### ISSUE TITLE
Juwelier plug in nakijken en het object diamond veranderen naar andere naam

### ISSUE THREAD

**Issue by Hagrid123** [pelikaanjpeg/TDAFiveM#161]

**Comment by Willem-Dekker** [comment]
Graag meer uitleg

**Comment by Hagrid123** [comment]
Wat er aan de hand is dat er een object in deze juwelier overval zit, dat ook in de mijn zit. Daarom moeten we eigenlijk het object anders maken in die richting. Ik weet niet exact hoe je dat doet, maa wist wel dat het kon.

**Comment by Willem-Dekker** [comment]
> Wat er aan de hand is dat er een object in deze juwelier overval zit, dat ook in de mijn zit. Daarom moeten we eigenlijk het object anders maken in die richting. Ik weet niet exact hoe je dat doet, maa wist wel dat het kon.

weet niet hele maal waar deze juwelier overval moet betekenen, waar wat en hoe kan ik dit testen?

**Comment by Hagrid123** [comment]
Ik weet toevallig ook niet waar het staat, moet je eens aan Niek vragen. Ik dacht dat ie in test server al zat. Want ze hadden ervoor al eens getest alleen heb je een object die diamond noemt/gebruikt en die moet veranderd worden. Alleen weet noet waar die in de files/bestanden staat. Zo niet moet je even kijken bij fiveM site, daar staat de plug in sws, of terug scrolle bij server suggesties.
