### ISSUE TITLE
Auto's verdwijnen spontaan

### ISSUE THREAD

**Issue by StoffigKontje** [pelikaanjpeg/TDAFiveM#164]
Auto's van spelers verdwijnen spontaan. Krijg de laatste tijd veel meldingen dat er auto's spontaan verdwijnen terwijl de spelers gewoon in de buurt zijn van het voertuig. Ik weet niet zo goed hoe je het moet re-creeeren, want het is puur willekeurig voor zover ik weet.

**Comment by Willem-Dekker** [comment]
is gtav engine
