### ISSUE TITLE
Claxons van motoren gaan constant af voor de mensen om je heen.

### ISSUE THREAD

**Issue by StoffigKontje** [pelikaanjpeg/TDAFiveM#165]
Bij veel motoren krijg ik te horen dat de mensen om de motor heen een constante claxon horen, terwijl de eigenaar van de motor dit niet hoort. Zelf heb ik het meerdere malen gehad met de politie motor, het lijkt te gebeuren wanneer ik de motor op slot zet of van het slot haal. Ik weet alleen niet zeker of het alleen daardoor komt.

**Comment by Willem-Dekker** [comment]
Er is op dit moment geen idee wat dit is, logging kunnen we ook niks mee
