### ISSUE TITLE
Mobiel kan geen foto’s maken

### ISSUE THREAD

**Issue by StoffigKontje** [pelikaanjpeg/TDAFiveM#168]
Wanneer je naar iemand een foto wil sturen via berichten met je mobiel, doet hij het niet. Hij doet er heel lang over om de animatie van het foto maken af te ronden, maar heeft dan uiteindelijk geen foto gemaakt en verstuurd.

**Comment by niekschoemaker** [comment]
Ja dat komt omdat webpack broken is :snail:
Ben al poosje bezig het proberen te fixen maar lukt niet echt, de screenshots zijn afhankelijk van screenshot-basic dacht ik zo uit m'n hoofd (zelfde als EasyAdmin screenshots) dus vandaar dat ze beide niet werken
