### ISSUE TITLE
Job bugfixes

### ISSUE THREAD

**Issue by Willem-Dekker** [pelikaanjpeg/TDAFiveM#172]
# Visser

* Alle icoontjes te vinden op de map
* €300 borg voor het bedrijfsvoertuig
* €300 borg voor de bedrijfsboot
* 100 vis
* €6 per vis: €600
* Op 25 minuten tijd verdien je: €600
* Op 1 uur tijd verdien je: €1200 * 4.5

## Bugs

- [x] De borg voor de boot & voor de wagen krijg je  niet terug (€600 kwijt)
- [x] De boot verliest veel te snel zijn benzine
- [x] De wagen kan je niet terug in de garage zetten

## verbeteringen

- [x] Fix de brandstof van de boot want je geraakt niet heen en terug op zee
- [x] Fix de garage van de bedrijfswagen

# Olie verwerker 

* Alle icoontjes te vinden op de map
* €300 borg voor het bedrijfsvoertuig
* 24 olie → 12 verfijnde olie → 24 essence

## Bugs
- [ ] De olietank die je op je truck draagt, kan je onmogelijk mee op zand rijden
- [ ] Olietank gaat ook maar max 60 p/u op de snelweg
- [x] De bedrijfswagen kun je niet terug in de garage zetten

## Verbetringen
- [ ] Fix de snelheid
- [x] Fix de garage
- [ ] Fix de verdiensten

# Vuilnisman
* Alle icoontjes te vinden op de map
* €400 betaald voor het bedrijfsvoertuig
* Op 20 minuten tijd verdien je: €2000
* Op 1 uur tijd verdien je: €6000

## Bugs
- [ ] Heel vaak dat je 2x op dezelfde plaats het vuil moet ophalen na elkaar

## Verbeterpunten
- [ ] Zorg ervoor dat je niet bij elke locatie 2x het vuil moet ophalen na elkaar

# Houthakker
* Niet alle icoontjes te vinden op de map
* 20 hout → 20 gesneden hout → 40 planken
* €22 per plank: €880
* Op 25 minuten tijd verdien je: €880
* Op 1 uur tijd verdien je: €1760 * 3.0

## Bugs
- [x] Er is geen bedrijfsvoertuig
- [x] Kledij voor vrouwen klopt niet helemaal (t-shirt komt uit torso)
- [x] Geen icoontje voor het versnijden van hout
- [x] Geen icoontje voor het maken van planken

## Verbeterpunten
 -
# Mijnwerker  
* €300 betaald voor het bedrijfsvoertuig
* 7 steen → 6 gewassen steen
* Stenen verschillen van prijzen
* Op 30 minuten tijd verdien je: €115
* Op 1 uur tijd verdien je: €230 * 3.0 (Zo’n laag bedrag?)

## Bugs
- [x] Gewassen steen weegt meer dan gewone steen
- [x] bedrijfsvoertuig kan je niet in de garage stoppen
- [x] Je kan de bedrijfswagen niet gebruiken om dingen in de koffer te steken (?)

## Verbeterpunten
- [x] Steen gewicht aanpassen
- [x] Fix de garage

# Zwembad verschoner 
* Alle icoontjes te vinden op de map
* Bedrijfsvoertuig betaal je hier geen waarborg voor
* 18 facturen
* €100 per 1 factuur = €1800
* Op 30 minuten tijd verdien je: €1800
* Op 1 uur tijd verdien je: €3600 * 1.5

## Bugs
- [ ] Er staat ook een random zwevende rode streep op de baan dat de garage zou moeten zijn
- [ ] Sommige plaatsen staan helemaal niet bij een zwembad
- [ ] Kledij broek klopt niet
- [ ] “Werk be[]indigen” als je uit dienst gaat
- [x] Garage werkt niet
- [x] Als je dienst er op zit, geeft hij nog elke keer een nieuwe route aan waar je geen factuur voor krijgt
- [x] Als je uit dienst gaat, blijft zo'n geel stipje op de map staan, zelfs als je veranderd van job

## Verbeterpunten
- [x] Fix de garage & de garage cirkel
- [ ] werk kledij zou moeten aangepast worden
- [ ] Plaatsen dichter bij het zwembad zetten

# Berging 
* Alle icoontjes te vinden op de map
* Je betaald geen geld om een boot te gebruiken
* 15 stuks
* €100 per stuk: €1500 (360 per stuk nu, was 180)
* Op 1u en 10 minuten verdien je: €1500 * 2.0

## Bugs
- [ ] Je verliest heel snel benzine met de boot
- [ ] Je moet soms de halve map rond varen en dat kost je al bijna 2 keer tanken
- [ ] sommige plaatsen zijn heel diep om te duiken en hebben niet eens een wrak in hun omgeving

## Verbeterpunten
- [x] De boot verliest veel te snel zijn benzine, dus mss dat hier naar gekeken kan worden
- [ ] Het is 1 van de mooiste jobs in de stad, maar spijtig genoeg doe je telkens meer dan een uur over om op het einde van je shift maar €1500 te krijgen (hmm, ik zag 180 per contrat dingetje staan, heb dit verhoogd naar 360)

# Slager 
* Niet alle icoontjes te vinden op de map
* €300 betaald voor het bedrijfsvoertuig
* €6 per kipfilet: €420 (70)
* Op 30 minuten verdien je: €420 (met 70 stuks)
* Op 1 uur verdien je: €840 (met 70 stuks) * 4

## Bugs
- [ ] 1 kip is 3kg, maximum kippen die je kan dragen zijn 5. Je moet elke keer naar je koffer lopen om ze daar in te dumpen
- [ ] Kippen verpakken staat niet op de map

## Verbeterpunten
- [x] Fix de garage
- [x] Een oplossing vinden dat je meer dan 5 kip in je inventory kan dragen (ik heb limieten uit jobs plugin gehaald, nu is het dus puur op gewicht)

# Kleermaker 
* Niet alle icoontjes zijn te vinden
* €300 voor het bedrijfsvoertuig
* Wol → Doeken → Kleding (30)
* €12 per Kledij: €180
* Per 25 minuten verdien je €180 (met 30 stuks) * 3.0
* Per 1 uur verdien je €360 (met 30 stuks)

## Bugs
- [x] Niet alle icoontjes zijn terug te vinden zoals het wol maken of kledij maken
- [x] Bedrijfsvoertuig kan je niet terug in de garage steken
- [x] Wol weegt 0,5kg – doeken wegen 0,25

## Verbeterpunten
- [x] Fix de garage
- [x] Misschien eens kijken naar het gewicht van wol

# Vrachtwagen chauffeur 
* 
* 

## Bugs
- [ ] Deze job kan niet worden uitgeoefend, er is nergens iets te vinden op de map

## Verbeterpunten
- [ ] Fix pls
- [x] Easy fix, hippity hoppity, whitelist eropity

# Ramenwasser 
* €300 voor de bedrijfswagen
* €100 per 'salvage': €2000
* Per 30 minuten verdien je: €2000
* Per 1 uur verdien je: €4000
 

## Bugs
- [x] Als je ramen hebt gewassen krijg je er 'salvage' voor
- [x] Je krijgt de huur van de bedrijfswagen niet terug

## Verbeterpunten
- [x] Naam veranderen van salvage naar factuur

**Comment by niekschoemaker** [comment]
Garage bugs waren van 1 plugin afkomstig, is gefixed.

Was een hash die niet correct omgerekend werd naar GetHashKey.
zie: [Fix job vehicles not being deleted ](https://github.com/niekschoemaker/fivem_server/commit/4eaca3da9cfb93c90c41a54a05afe2c81a0a5142)
