### ISSUE TITLE
Sneeuw schuiver weg halen bij PostNL busje

### ISSUE THREAD

**Issue by SecretSupplier** [pelikaanjpeg/TDAFiveM#50]

**Comment by Ventrex** [comment]
Als ik hem handmatig inspawn zie ik hem niet. (/car burrito3)

**Comment by Ventrex** [comment]
Ik kan niets vinden om de ytd of ytr files te editen. Alle extra’s zouden van de auto afgehaald moeten worden trouwens. Want hij heeft ook buizen en ladders bij zich.

**Comment by niekschoemaker** [comment]
Gefixxed door Kenneth als het goed is
