### ISSUE TITLE
Huur en Prijs woning is niet zichtbaar

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#54]
Alleen met kopen en huren is het zichtbaar. (maar dus te laat)

**Comment by Ventrex** [comment]
Koop prijs is wel zichtbaar maar scherm te vroeg.
Wanneer je de koop prijs selecteert krijg je Kopen of VERhuren (is ook onjuist moet huren zijn)
Huur prijs is niet zichtbaar en beste is om eerst je keuze te maken en bij Huren en Kopen de prijs op te geven.

**Comment by Willem-Dekker** [comment]
gemaakt
