### ISSUE TITLE
Voor “illigale” jobs witwassen en wietplantages wel zichtbaar maken

### ISSUE THREAD

**Issue by Ventrex** [pelikaanjpeg/TDAFiveM#69]

**Comment by Willem-Dekker** [comment]
Het is volgens mij de bedoeling dat je die moet vinden en dat die niet voor iedereen zichtbaar zijn

**Comment by Ventrex** [comment]
Ja maar als je in de mafia zit moet je toch weten waar je je wiet hebt gepland?

**Comment by Willem-Dekker** [comment]
nee, die moeten het ook vinden

**Comment by Ventrex** [comment]
Degene die de wiet heeft geplaatst hoor te zien waar die het plaatst. Dus als ik als Mafia de wiet plant dan moet ik toch weten waar dat is gebeurd.
