### ISSUE TITLE
1. Beloning reanimeren

### ISSUE THREAD

**Issue by SecretSupplier** [pelikaanjpeg/TDAFiveM#95]
2. Zodra je een persoon reanimeerdt moet je een beloning krjigen van 100$ zodat de ambu of de politie een directe beloning krijgt voor de daad die ze verichten.

**Comment by Ventrex** [comment]
Misschien meer geld? €100 is mooi maar het gebeurd niet zo vaak

**Comment by Willem-Dekker** [comment]
is van 700 naar 300 gebracht, politie kan momenteel nog niet reanimeeren.
